### ISSUE TITLE
Compile issues after upgrading to 2.2.0

### ISSUE THREAD

**Issue by iosephmagno** [aws-amplify/amplify-flutter#5165]
### Description

After upgrading to latest flutter master channel and upgrading Amplify to 2.2.0, I get several compile issues that I cannto solve:

```
// Error
error: cannot find symbol
      flutterEngine.getPlugins().add(new com.amazonaws.amplify.amplify_secure_storage.AmplifySecureStoragePlugin());
```

```
// Warnings 
Package amplify_secure_storage:linux references amplify_secure_storage_dart:linux as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: linux: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

Package amplify_secure_storage:windows references amplify_secure_storage_dart:windows as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: windows: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

Package amplify_secure_storage:linux references amplify_secure_storage_dart:linux as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: linux: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

Package amplify_secure_storage:windows references amplify_secure_storage_dart:windows as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: windows: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

Package amplify_secure_storage:linux references amplify_secure_storage_dart:linux as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: linux: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

Package amplify_secure_storage:windows references amplify_secure_storage_dart:windows as the default plugin, but the package does not exist.
Ask the maintainers of amplify_secure_storage to either avoid referencing a default implementation via `platforms: windows: default_package: amplify_secure_storage_dart` or create a plugin named amplify_secure_storage_dart.

```

My pubspec is:
```
  amplify_auth_cognito: 2.2.0
  amplify_flutter: 2.2.0 
  amplify_storage_s3: 2.2.0 
  amplify_authenticator: 2.1.0 
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Set pubspec as follow and compile

```
  amplify_auth_cognito: 2.2.0
  amplify_flutter: 2.2.0 
  amplify_storage_s3: 2.2.0 
  amplify_authenticator: 2.1.0 
```

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

Channel Master  3.24.0-1.0.pre.151

### Amplify Flutter Version

2.2.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hi @iosephmagno, thank's for reporting this. 

Due to frequent changes in the Flutter Master channel, issues like this can occasionally occur (and even resolve themselves). However, we will investigate to ensure this won't be an issue long term.

**Comment by delfme** [comment]
Other plugin had to fix same issue as well, please check here https://github.com/MaikuB/flutter_local_notifications/issues/2368

**Comment by Equartey** [comment]
@iosephmagno @delfme

Hi all, a fix for this has been merged. We will let yall know when this has been released. Thanks again for reporting it.

**Comment by iosephmagno** [comment]
Hello, just informing that we tried latest version of plugin and still throws compile errors. We have to downgrade to amplify v. 1.7.0 to be able to compile.

**Comment by MarlonJD** [comment]
> Hello, just informing that we tried latest version of plugin and still throws compile errors. We have to downgrade to amplify v. 1.7.0 to be able to compile.

Which version on flutter? Is this master branch of flutter? This changes merged but not available on 2.2.0, these changes not released yet, so you might get build error while you trying to build on latest flutter version.

**Comment by iosephmagno** [comment]
Yep master branch,  I'm not at deck now and can't say the version, but a recent one.

**Comment by NikaHsn** [comment]
@iosephmagno @delfme the fix bas been merged and will be released in the next version.

**Comment by jamontesg** [comment]
this was solved on todays release ?

**Comment by delfme** [comment]
Thx guys! 🚀

**Comment by NikaHsn** [comment]
I'm going to close this issue as the fix has been released in [2.4.0](https://github.com/aws-amplify/amplify-flutter/releases/tag/v2.4.0) version. If you see otherwise or have additional questions, please open a new issue.
